name: Build

on:
    push:
        paths-ignore:
            - README.md
            - .gitignore
            - .github/**
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [16.x]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - name: npm install, build, and test
              run: |
                  npm install
                  npm run start -- --testMode
                  npm run demo
                  npm run coverage
              env:
                  CI: true
            - name: Deploy to GitHub Pages 🚀
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./demo
